/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latentsemanticindexing.control;

import Data.Data;
import UI.Dictionary;
import com.sun.javafx.geom.Vec2d;
import de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.text.ParseException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author quocn
 */
public class Documents extends javax.swing.JFrame {

    /**
     * Creates new form Documents
     */
    
    private static Documents instance = null;
    
    public Documents() throws Exception {
        initComponents();
        loadDocumentNames();
    }
    
    public void loadDocumentNames() throws Exception{
        
        comboBoxNameDocument.removeAllItems();
        
        String sql = "select name_collection from information";
        
        ResultSet res = Data.getResultsetQuery(sql, "lsi");
        while(res.next()){
            comboBoxNameDocument.addItem(res.getString(1));
        }
        comboBoxNameDocument.addItem(Dictionary.Words.ADD_NEW_DOCUMENT.getString() + "...");
    }
    
    public static Documents getInstance() throws Exception{
        if(instance == null) instance = new Documents();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaText = new javax.swing.JTextArea();
        textName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonDone = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textConfirm = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBoxNameDocument = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaText.setColumns(20);
        textAreaText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textAreaText.setRows(5);
        jScrollPane1.setViewportView(textAreaText);

        textName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name Document:");

        buttonDone.setText("DONE");
        buttonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDoneActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DOCUMENT");

        textConfirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Choose Document:");

        comboBoxNameDocument.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxNameDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNameDocumentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(buttonDone)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxNameDocument, 0, 317, Short.MAX_VALUE)
                                    .addComponent(textName))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxNameDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonDone)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(textConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDoneActionPerformed
        try {
            String name = textName.getText();
            String text = textAreaText.getText();
            addDocument(name, text);
            addTermWord(name, text);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_buttonDoneActionPerformed

    private void addDocument(String name, String text) throws Exception{
        boolean confirm = true;
        try{
            
            
            if(name.isEmpty() || text.isEmpty()){
                textConfirm.setText("Khong duoc bo trong");
                throw new Exception();
            }

            String sql = "INSERT INTO documents VALUES (null, '" 
                        + name + "', '" + text + "');";
            String collectionName = (String) comboBoxNameDocument.getSelectedItem();
            String databaseName = getDatabaseName(collectionName);
            Data.setResultsetUpdate(sql, databaseName );
        }catch(Exception ex){
            ex.printStackTrace();
            confirm = false;
            
        }finally{
            if(confirm){
                textConfirm.setForeground(Dictionary.COLOR.SUCCESSFUL.getColor());
                textConfirm.setText(Dictionary.Words.INSERT.getString() + " "
                        +Dictionary.Words.SUCCESSFUL.getString());

                clearComponent();
            }else{
                Toolkit.getDefaultToolkit().beep();
                textConfirm.setForeground(Dictionary.COLOR.FAIL.getColor());
                textConfirm.setText(Dictionary.Words.INSERT.getString() + " " 
                        +Dictionary.Words.FAIL.getString());
            }
        }
    }
    
    private String getDatabaseName(String collectionName){
        String sql = "select name_database from information where name_collection = '"
                + collectionName + "'";
        try{
            ResultSet res =  Data.getResultsetQuery(sql, "lsi");
            res.next();
            return res.getString(1);
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return null;
    }
    
    private void addTermWord(String name, String text){
        Vector listTermWord = RemoveStopWord.getList(text);
        for(int i=0; i<listTermWord.size(); ++i){
            String word = (String) listTermWord.get(i);
            checkWord(word);
            
            
        }
    }
    
    private void checkWord(String word){
        String sql = "select top 1 word from terms";
        ResultSet res;
        try {
            res = Data.getResultsetQuery(sql, comboBoxNameDocument.getSelectedItem().toString());
            if(res.next()){
                return;
            }
            sql = "INSERT INTO terms VALUES (null, '" + word + "')";
        } catch (Exception ex) {
        }
        
    }
    
    private void comboBoxNameDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNameDocumentActionPerformed
        // TODO add your handling code here:
        if(comboBoxNameDocument.getSelectedIndex() == comboBoxNameDocument.getItemCount() - 1 
                && comboBoxNameDocument.getSelectedIndex() > 0){
                AddNewDocument.getIntance(comboBoxNameDocument).setVisible(true);
        }
    }//GEN-LAST:event_comboBoxNameDocumentActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new SyntheticaBlueLightLookAndFeel());
        } catch (ParseException | UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Documents().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Documents.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDone;
    private javax.swing.JComboBox<String> comboBoxNameDocument;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaText;
    private javax.swing.JLabel textConfirm;
    private javax.swing.JTextField textName;
    // End of variables declaration//GEN-END:variables

    private void clearComponent() {
        textAreaText.setText("");
        textName.setText("");
    }
}
